version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - ${UNWEAVE_API_PORT}:${UNWEAVE_API_PORT}
    expose:
      - ${UNWEAVE_API_PORT}
    environment:
      UNWEAVE_API_PORT: ${UNWEAVE_API_PORT}
    working_dir: /home/unweave
    volumes:
      - ./:/home/unweave
      - ~/.unweave/runtime-config.json:/root/.unweave/runtime-config.json
